#!/bin/sh
if [ -f /tmp/XionHDF/skin.xml ]; then
	rm -rf /usr/share/enigma2/XionHDF/
	mv /tmp/XionHDF /usr/share/enigma2/
fi
echo "                                                          "
echo "             ...Skin successful installed.                "
echo "                                                          "
