#!/bin/sh
echo "Checking for previous installations..."
if [ -f /usr/share/enigma2/XionHDF/skin.xml ]; then
    cp -R /usr/share/enigma2/XionHDF/ /tmp
    rm -rf /usr/share/enigma2/XionHDF
    rm -rf /usr/lib/enigma2/python/Components/Converter/XionHDF*
    rm -rf /usr/lib/enigma2/python/Components/Renderer/XionHDF*
		echo "                                                           "
		echo "             Previous XionHDF installation                 "
		echo "                 was found and removed!                    "
		echo "                                                           "
fi
if [ -f /usr/lib/enigma2/python/Plugins/Extensions/XionHDF/plugin.py ]; then
    rm -rf /usr/lib/enigma2/python/Plugins/Extensions/XionHDF
		echo "                                                           "
		echo "              XionHDF configuration plugin                 "
		echo "                 was found and removed!                    "
		echo "                                                           "
fi




echo "                                                           "
echo "         The Skin XionHDF is now being installed...        "
echo "                                                           "



