#!/bin/sh
echo "                                                           "
echo "         The Skin XionHDF is now being removed...          "
echo "                                                           "
